% calculate_min_distance
%
% 431-400 Year Long Project, LA1 - Medical Image Processing 2003
% Supervisor     :  Dr Lachlan Andrew
% Group Members  :  Alister Fong    78629   a.fong1@ugrad.unimelb.edu.au
%                   Lee Siew Teng   102519  s.lee1@ugrad.unimelb.edu.au
%                   Loh Jien Mei    103650  j.loh1@ugrad.unimelb.edu.au
%
% test_calculate_min_distance.m (RUN THIS!!)
%       Test the function "test_calculate_min_distance"
% calculate_min_distance.m (USE THIS!!)
% 	Calculates the minimum distance between 2 edges and returns the distance and
% 	the matrix linking the coordinates to both edge coordinates.
% euclidean_distance.m (USE THIS!!)
%         Calculates the euclidean_distance between 2 points